//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""DiceRolling"",
            ""id"": ""c47206a5-695e-41ff-9a65-4c3b29212662"",
            ""actions"": [
                {
                    ""name"": ""RollDice"",
                    ""type"": ""Button"",
                    ""id"": ""f2fa172b-12cf-423d-88bd-ea7587f9439d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""84834df7-25fc-4c19-9869-bfbfdf8f409b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ff9c44e2-941f-4be3-a041-5eeef74f2010"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RollDice"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""22bc18b9-426c-4541-b79c-c20509d6f5de"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RollDice"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""67cd4d93-4a5e-4e01-a09a-749f2e513ad2"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RollDice"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4bbe5494-24c9-40fc-a2ae-c53257cd143a"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // DiceRolling
        m_DiceRolling = asset.FindActionMap("DiceRolling", throwIfNotFound: true);
        m_DiceRolling_RollDice = m_DiceRolling.FindAction("RollDice", throwIfNotFound: true);
        m_DiceRolling_Attack = m_DiceRolling.FindAction("Attack", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // DiceRolling
    private readonly InputActionMap m_DiceRolling;
    private IDiceRollingActions m_DiceRollingActionsCallbackInterface;
    private readonly InputAction m_DiceRolling_RollDice;
    private readonly InputAction m_DiceRolling_Attack;
    public struct DiceRollingActions
    {
        private @PlayerInputActions m_Wrapper;
        public DiceRollingActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @RollDice => m_Wrapper.m_DiceRolling_RollDice;
        public InputAction @Attack => m_Wrapper.m_DiceRolling_Attack;
        public InputActionMap Get() { return m_Wrapper.m_DiceRolling; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DiceRollingActions set) { return set.Get(); }
        public void SetCallbacks(IDiceRollingActions instance)
        {
            if (m_Wrapper.m_DiceRollingActionsCallbackInterface != null)
            {
                @RollDice.started -= m_Wrapper.m_DiceRollingActionsCallbackInterface.OnRollDice;
                @RollDice.performed -= m_Wrapper.m_DiceRollingActionsCallbackInterface.OnRollDice;
                @RollDice.canceled -= m_Wrapper.m_DiceRollingActionsCallbackInterface.OnRollDice;
                @Attack.started -= m_Wrapper.m_DiceRollingActionsCallbackInterface.OnAttack;
                @Attack.performed -= m_Wrapper.m_DiceRollingActionsCallbackInterface.OnAttack;
                @Attack.canceled -= m_Wrapper.m_DiceRollingActionsCallbackInterface.OnAttack;
            }
            m_Wrapper.m_DiceRollingActionsCallbackInterface = instance;
            if (instance != null)
            {
                @RollDice.started += instance.OnRollDice;
                @RollDice.performed += instance.OnRollDice;
                @RollDice.canceled += instance.OnRollDice;
                @Attack.started += instance.OnAttack;
                @Attack.performed += instance.OnAttack;
                @Attack.canceled += instance.OnAttack;
            }
        }
    }
    public DiceRollingActions @DiceRolling => new DiceRollingActions(this);
    public interface IDiceRollingActions
    {
        void OnRollDice(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
    }
}
